[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/apps/admin/*"
  to = "/apps/admin/index.html"
  status = 200

[[redirects]]
  from = "/apps/auth/*"
  to = "/apps/auth/index.html"
  status = 200
