[[redirects]]
  from = "/admin"
  to = "/apps/admin/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/apps/admin/:splat"
  status = 200

[[redirects]]
  from = "/apps/*"
  to = "/apps/:splat"
  status = 200
